"""Small aiosqlite-compatible adapter backed by PostgreSQL/asyncpg.

This keeps the existing project API mostly unchanged while moving storage to PostgreSQL.
"""
import os
import re
import asyncpg

Row = object


def _dsn(value):
    value = value or os.getenv("DATABASE_URL", "")
    if value.startswith("postgres://"):
        value = "postgresql://" + value[len("postgres://"):]
    if not value:
        raise RuntimeError("DATABASE_URL is not configured")
    return value


def _convert_sql(sql: str) -> str:
    # SQLite -> PostgreSQL syntax used by this project.
    sql = re.sub(r"\bAUTOINCREMENT\b", "GENERATED BY DEFAULT AS IDENTITY", sql, flags=re.I)
    sql = re.sub(r"\bMIN\s*\(", "LEAST(", sql, flags=re.I)
    sql = re.sub(r"\bMAX\s*\(", "GREATEST(", sql, flags=re.I)
    sql = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", sql, flags=re.I)
    # The only INSERT OR IGNORE in the project has a conflict-free primary key.
    if re.match(r"\s*INSERT INTO", sql, flags=re.I) and "ON CONFLICT" not in sql.upper() and "OR IGNORE" in sql.upper():
        sql = re.sub(r"\s+OR\s+IGNORE", "", sql, flags=re.I)
        sql += " ON CONFLICT DO NOTHING"
    # Convert SQLite's ? parameters to PostgreSQL's $1, $2, ...
    parts = []
    idx = 0
    in_single = False
    in_double = False
    i = 0
    while i < len(sql):
        ch = sql[i]
        if ch == "'" and not in_double:
            if in_single and i + 1 < len(sql) and sql[i + 1] == "'":
                parts.append("''")
                i += 2
                continue
            in_single = not in_single
        elif ch == '"' and not in_single:
            in_double = not in_double
        if ch == "?" and not in_single and not in_double:
            idx += 1
            parts.append(f"${idx}")
        else:
            parts.append(ch)
        i += 1
    return "".join(parts)


class Cursor:
    def __init__(self, rows):
        self.rows = rows
        self.pos = 0

    async def fetchone(self):
        if self.pos >= len(self.rows):
            return None
        row = self.rows[self.pos]
        self.pos += 1
        return row

    async def fetchall(self):
        rows = self.rows[self.pos:]
        self.pos = len(self.rows)
        return rows


class Connection:
    def __init__(self, dsn):
        self.dsn = _dsn(dsn)
        self.conn = None
        self.row_factory = None

    async def __aenter__(self):
        self.conn = await asyncpg.connect(self.dsn)
        return self

    async def __aexit__(self, exc_type, exc, tb):
        if self.conn:
            await self.conn.close()

    async def execute(self, sql, args=()):
        sql = _convert_sql(sql)
        args = tuple(args or ())
        if re.match(r"\s*(SELECT|WITH|SHOW)\b", sql, re.I):
            return Cursor(await self.conn.fetch(sql, *args))
        await self.conn.execute(sql, *args)
        return Cursor([])

    async def executemany(self, sql, seq):
        sql = _convert_sql(sql)
        await self.conn.executemany(sql, list(seq))

    async def executescript(self, script):
        # init_db uses a plain schema script without procedural SQL.
        statements = [s.strip() for s in script.split(";") if s.strip()]
        for statement in statements:
            await self.execute(statement)

    async def commit(self):
        # asyncpg statements are committed automatically when not inside an explicit transaction.
        return None

    async def rollback(self):
        return None


def connect(database=None, *args, **kwargs):
    return Connection(database)
