"""SQLite-compatible async adapter backed by PostgreSQL/asyncpg."""
import os
import re
import asyncpg

Row = object

# Tables in this project whose primary key is an identity column.
_ID_TABLES = {
    "spirits", "warnings", "admin_logs", "shop_items", "regions",
    "spirits_story", "spirit_clues", "demons", "marriages", "children",
}

def _dsn(value):
    value = value or os.getenv("DATABASE_URL", "")
    if value.startswith("postgres://"):
        value = "postgresql://" + value[len("postgres://"):]
    if not value:
        raise RuntimeError("DATABASE_URL is not configured")
    return value

def _convert_sql(sql: str) -> str:
    sql = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
                 "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", sql, flags=re.I)
    sql = re.sub(r"\bAUTOINCREMENT\b",
                 "GENERATED BY DEFAULT AS IDENTITY", sql, flags=re.I)
    sql = re.sub(r"\bMIN\s*\(", "LEAST(", sql, flags=re.I)
    sql = re.sub(r"\bMAX\s*\(", "GREATEST(", sql, flags=re.I)
    # SQLite conflict syntax.
    m = re.search(r"INSERT\s+OR\s+IGNORE\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)", sql, flags=re.I)
    if m:
        sql = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", sql, count=1, flags=re.I)
        if "ON CONFLICT" not in sql.upper():
            sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return _convert_params(sql)

def _convert_params(sql: str) -> str:
    parts, i, idx = [], 0, 0
    in_single = in_double = False
    while i < len(sql):
        ch = sql[i]
        if ch == "'" and not in_double:
            if in_single and i + 1 < len(sql) and sql[i + 1] == "'":
                parts.append("''"); i += 2; continue
            in_single = not in_single
        elif ch == '"' and not in_single:
            in_double = not in_double
        if ch == "?" and not in_single and not in_double:
            idx += 1
            parts.append(f"${idx}")
        else:
            parts.append(ch)
        i += 1
    return "".join(parts)

class Cursor:
    def __init__(self, rows=None, lastrowid=None):
        self.rows = list(rows or [])
        self.pos = 0
        self.lastrowid = lastrowid

    async def fetchone(self):
        if self.pos >= len(self.rows):
            return None
        row = self.rows[self.pos]; self.pos += 1
        return row

    async def fetchall(self):
        rows = self.rows[self.pos:]
        self.pos = len(self.rows)
        return rows

class Connection:
    def __init__(self, dsn):
        self.dsn = _dsn(dsn)
        self.conn = None
        self.row_factory = None

    async def __aenter__(self):
        self.conn = await asyncpg.connect(self.dsn)
        return self

    async def __aexit__(self, exc_type, exc, tb):
        if self.conn:
            await self.conn.close()

    async def execute(self, sql, args=()):
        original = sql
        sql = _convert_sql(sql)
        args = tuple(args or ())

        if re.match(r"\s*(SELECT|WITH|SHOW)\b", sql, re.I):
            return Cursor(await self.conn.fetch(sql, *args))

        # Preserve the old aiosqlite lastrowid behavior for identity tables.
        lastrowid = None
        m = re.match(r"\s*INSERT\s+(?:INTO)\s+([A-Za-z_][A-Za-z0-9_]*)\b", sql, re.I)
        if m and m.group(1).lower() in _ID_TABLES and "RETURNING" not in sql.upper():
            sql = sql.rstrip().rstrip(";") + " RETURNING id"
            rows = await self.conn.fetch(sql, *args)
            if rows:
                lastrowid = rows[0]["id"]
            return Cursor(rows, lastrowid=lastrowid)

        await self.conn.execute(sql, *args)
        return Cursor([], lastrowid=lastrowid)

    async def executemany(self, sql, seq):
        sql = _convert_sql(sql)
        await self.conn.executemany(sql, list(seq))

    async def executescript(self, script):
        statements = [s.strip() for s in script.split(";") if s.strip()]
        for statement in statements:
            await self.execute(statement)

    async def commit(self):
        return None

    async def rollback(self):
        return None

def connect(database=None, *args, **kwargs):
    return Connection(database)
