"""SQLite-compatible async adapter backed by PostgreSQL/asyncpg."""
import os
import re
import asyncpg

Row = object

# Tables in this project whose primary key is an identity column.
_ID_TABLES = {
    "spirits", "warnings", "admin_logs", "shop_items", "regions",
    "spirits_story", "spirit_clues", "demons", "marriages", "children",
}

def _dsn(value):
    value = value or os.getenv("DATABASE_URL", "")
    if value.startswith("postgres://"):
        value = "postgresql://" + value[len("postgres://"):]
    if not value:
        raise RuntimeError("DATABASE_URL is not configured")
    return value

def _convert_sql(sql: str) -> str:
    sql = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
                 "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", sql, flags=re.I)
    sql = re.sub(r"\bAUTOINCREMENT\b",
                 "GENERATED BY DEFAULT AS IDENTITY", sql, flags=re.I)
    # Note: do NOT rewrite MIN()/MAX() — they are valid aggregate functions in both SQLite and PostgreSQL.
    # LEAST/GREATEST are for multi-arg scalar comparison; rewriting would break SELECT MIN(col).
    # SQLite conflict syntax.
    m = re.search(r"INSERT\s+OR\s+IGNORE\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)", sql, flags=re.I)
    if m:
        sql = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", sql, count=1, flags=re.I)
        if "ON CONFLICT" not in sql.upper():
            sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return _convert_params(sql)

def _convert_params(sql: str) -> str:
    parts, i, idx = [], 0, 0
    in_single = in_double = False
    while i < len(sql):
        ch = sql[i]
        if ch == "'" and not in_double:
            if in_single and i + 1 < len(sql) and sql[i + 1] == "'":
                parts.append("''"); i += 2; continue
            in_single = not in_single
        elif ch == '"' and not in_single:
            in_double = not in_double
        if ch == "?" and not in_single and not in_double:
            idx += 1
            parts.append(f"${idx}")
        else:
            parts.append(ch)
        i += 1
    return "".join(parts)

class Cursor:
    def __init__(self, rows=None, lastrowid=None, row_factory=None):
        self.rows = list(rows or [])
        self.pos = 0
        self.lastrowid = lastrowid
        self.row_factory = row_factory

    def _wrap(self, row):
        if row is None or self.row_factory is None:
            return row
        # asyncpg.Record already supports index + name access; leave as-is
        # unless a custom factory was requested (aiosqlite.Row is a no-op marker).
        if self.row_factory is Row or self.row_factory is object:
            return row
        try:
            return self.row_factory(row)
        except Exception:
            return row

    async def fetchone(self):
        if self.pos >= len(self.rows):
            return None
        row = self.rows[self.pos]
        self.pos += 1
        return self._wrap(row)

    async def fetchall(self):
        rows = self.rows[self.pos:]
        self.pos = len(self.rows)
        return [self._wrap(r) for r in rows]

class Connection:
    def __init__(self, dsn):
        self.dsn = _dsn(dsn)
        self.conn = None
        self.row_factory = None

    async def __aenter__(self):
        self.conn = await asyncpg.connect(self.dsn)
        return self

    async def __aexit__(self, exc_type, exc, tb):
        if self.conn:
            await self.conn.close()

    async def execute(self, sql, args=()):
        sql = _convert_sql(sql)
        args = tuple(args or ())

        if re.match(r"\s*(SELECT|WITH|SHOW)\b", sql, re.I):
            return Cursor(await self.conn.fetch(sql, *args), row_factory=self.row_factory)

        # Preserve the old aiosqlite lastrowid behavior for identity tables.
        lastrowid = None
        m = re.match(r"\s*INSERT\s+(?:INTO)\s+([A-Za-z_][A-Za-z0-9_]*)\b", sql, re.I)
        if m and m.group(1).lower() in _ID_TABLES and "RETURNING" not in sql.upper():
            sql = sql.rstrip().rstrip(";") + " RETURNING id"
            rows = await self.conn.fetch(sql, *args)
            if rows:
                lastrowid = rows[0]["id"]
            return Cursor(rows, lastrowid=lastrowid, row_factory=self.row_factory)

        await self.conn.execute(sql, *args)
        return Cursor([], lastrowid=lastrowid, row_factory=self.row_factory)

    async def executemany(self, sql, seq):
        sql = _convert_sql(sql)
        await self.conn.executemany(sql, list(seq))

    async def executescript(self, script):
        statements = [s.strip() for s in script.split(";") if s.strip()]
        for statement in statements:
            await self.execute(statement)

    async def commit(self):
        return None

    async def rollback(self):
        return None

def connect(database=None, *args, **kwargs):
    return Connection(database)
