const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();} const headers=()=>({'X-Telegram-Init-Data':tg?.initData||''});
const $=id=>document.getElementById(id); let me;
function showTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelector(`[data-tab="${id}"]`)?.classList.add('active');if(id==='inventory')loadInventory();if(id==='shop')loadShop();if(id==='stories')loadStories();}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function notice(t){$('notice').textContent=t;$('notice').classList.remove('hidden');setTimeout(()=>$('notice').classList.add('hidden'),2600)}
async function api(url,opt={}){opt.headers={...headers(),...(opt.headers||{})};const r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text()||'خطا');return r.json()}
async function loadMe(){try{me=await api('/api/me');['level','xp','coins','energy','mind','body','spirit','light'].forEach(k=>$(k).textContent=me[k]??0);const f=await api('/api/family');$('family').textContent=`💍 ازدواج‌ها: ${f.marriages.length}  •  👶 فرزندان: ${f.children.length}`;}catch(e){notice('ابتدا Web App را از داخل ربات باز کن.')}}
async function loadInventory(){try{const rows=await api('/api/inventory');$('inventoryList').innerHTML=rows.length?rows.map(x=>`<article class="card item"><div class="meta"><h3>${x.name} <span class="tag">×${x.quantity}</span></h3><p>${x.description}<br><span class="muted">⚡ +${x.energy_gain} انرژی • ✨ +${x.mission_bonus} قدرت</span></p></div><button onclick="useItem(${x.item_id})">استفاده</button></article>`).join(''):'<article class="card"><p>کیف خالی است.</p></article>'}catch(e){notice(e.message)}}
async function useItem(id){try{const x=await api(`/api/inventory/${id}/use`,{method:'POST'});notice(x.message);await Promise.all([loadMe(),loadInventory()])}catch(e){notice(e.message)}}
async function loadShop(){try{const rows=await api('/api/shop');$('shopList').innerHTML=rows.map(x=>`<article class="card item"><div class="meta"><h3>${x.name}</h3><p>${x.description}<br><span class="muted">🪙 ${x.price_coins} • 💎 ${x.price_gems}</span></p></div><button onclick="buy(${x.id})">خرید</button></article>`).join('')}catch(e){notice(e.message)}}
async function buy(id){try{const x=await api(`/api/shop/${id}/buy`,{method:'POST'});notice(x.message);await Promise.all([loadMe(),loadInventory()])}catch(e){notice(e.message)}}
async function loadStories(){try{const rows=await api('/api/stories');$('storyList').innerHTML=rows.map(x=>`<article class="card story"><h3>👻 ${x.name}</h3><p><span class="tag">${x.region_name}</span><span class="difficulty">سختی ${x.difficulty}/7</span></p><p>${x.story}</p><p><b>درخواست:</b> ${x.request}</p><p class="muted">🪙 ${x.reward_coins} • XP ${x.reward_xp}</p></article>`).join('')}catch(e){notice(e.message)}}
$('train').onclick=async()=>{try{const x=await api('/api/train/mind',{method:'POST'});notice(x.message);loadMe()}catch(e){notice(e.message)}};$('refresh').onclick=loadMe;$('invRefresh').onclick=loadInventory;loadMe();
