-- PostgreSQL schema for Spirit Guardian
-- Seed data is inserted automatically by init_db() on first startup.

CREATE TABLE IF NOT EXISTS users (
            user_id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            coins INTEGER NOT NULL DEFAULT 100,
            energy INTEGER NOT NULL DEFAULT 10,
            max_health INTEGER NOT NULL DEFAULT 100,
            health INTEGER NOT NULL DEFAULT 100,
            soul_gems INTEGER NOT NULL DEFAULT 0,
            xp INTEGER NOT NULL DEFAULT 0,
            level INTEGER NOT NULL DEFAULT 1,
            spirits_sent INTEGER NOT NULL DEFAULT 0,
            cleanses INTEGER NOT NULL DEFAULT 0,
            last_daily TEXT,
            gender TEXT,
            mind_power INTEGER NOT NULL DEFAULT 1,
            body_power INTEGER NOT NULL DEFAULT 1,
            spirit_power INTEGER NOT NULL DEFAULT 1,
            training_points INTEGER NOT NULL DEFAULT 0,
            last_training TEXT
        );

        CREATE TABLE IF NOT EXISTS spirits (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name TEXT NOT NULL,
            description TEXT NOT NULL,
            request TEXT NOT NULL,
            difficulty INTEGER NOT NULL DEFAULT 1,
            reward_coins INTEGER NOT NULL DEFAULT 50,
            reward_xp INTEGER NOT NULL DEFAULT 30,
            active INTEGER NOT NULL DEFAULT 1
        );

        CREATE TABLE IF NOT EXISTS user_spirits (
            user_id INTEGER NOT NULL,
            spirit_id INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            PRIMARY KEY(user_id, spirit_id)
        );

        CREATE TABLE IF NOT EXISTS staff (
            user_id INTEGER PRIMARY KEY,
            role TEXT NOT NULL DEFAULT 'ادمین',
            added_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS moderation (
            user_id INTEGER PRIMARY KEY,
            banned INTEGER NOT NULL DEFAULT 0,
            ban_until TEXT,
            reason TEXT
        );

        CREATE TABLE IF NOT EXISTS warnings (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user_id INTEGER NOT NULL,
            admin_id INTEGER NOT NULL,
            reason TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS admin_logs (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            admin_id INTEGER NOT NULL,
            action TEXT NOT NULL,
            target_id INTEGER,
            details TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS shop_items (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name TEXT NOT NULL,
            description TEXT NOT NULL,
            category TEXT NOT NULL,
            price_coins INTEGER NOT NULL DEFAULT 0,
            price_gems INTEGER NOT NULL DEFAULT 0,
            energy_gain INTEGER NOT NULL DEFAULT 0,
            mission_bonus INTEGER NOT NULL DEFAULT 0,
            quantity INTEGER NOT NULL DEFAULT 1,
            active INTEGER NOT NULL DEFAULT 1
        );

        CREATE TABLE IF NOT EXISTS inventory (
            user_id INTEGER NOT NULL,
            item_id INTEGER NOT NULL,
            quantity INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY(user_id, item_id)
        );

        CREATE TABLE IF NOT EXISTS regions (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name TEXT NOT NULL, description TEXT NOT NULL, unlock_level INTEGER NOT NULL DEFAULT 1, active INTEGER NOT NULL DEFAULT 1
        );

        CREATE TABLE IF NOT EXISTS spirits_story (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name TEXT NOT NULL, age INTEGER, type TEXT NOT NULL, region_id INTEGER NOT NULL,
            difficulty INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'سرگردان', request TEXT NOT NULL, story TEXT NOT NULL,
            reward_coins INTEGER NOT NULL DEFAULT 50, reward_xp INTEGER NOT NULL DEFAULT 30, active INTEGER NOT NULL DEFAULT 1
        );

        CREATE TABLE IF NOT EXISTS spirit_clues (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, spirit_id INTEGER NOT NULL, clue_order INTEGER NOT NULL, text TEXT NOT NULL, correct_option TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS spirit_progress (
            user_id INTEGER NOT NULL, spirit_id INTEGER NOT NULL, clue_index INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active',
            PRIMARY KEY(user_id, spirit_id)
        );

        CREATE TABLE IF NOT EXISTS demons (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name TEXT NOT NULL, type TEXT NOT NULL, rank INTEGER NOT NULL DEFAULT 1,
            power INTEGER NOT NULL DEFAULT 50, defense INTEGER NOT NULL DEFAULT 20, health INTEGER NOT NULL DEFAULT 100, corruption INTEGER NOT NULL DEFAULT 100,
            temperament TEXT NOT NULL, ability TEXT NOT NULL, story TEXT NOT NULL, region_id INTEGER NOT NULL, reward_coins INTEGER NOT NULL DEFAULT 80, reward_xp INTEGER NOT NULL DEFAULT 50, active INTEGER NOT NULL DEFAULT 1
        );

        CREATE TABLE IF NOT EXISTS demon_encounters (
            user_id INTEGER NOT NULL, demon_id INTEGER NOT NULL, health INTEGER NOT NULL, corruption INTEGER NOT NULL, stage INTEGER NOT NULL DEFAULT 1,
            status TEXT NOT NULL DEFAULT 'active', PRIMARY KEY(user_id, demon_id)
        );

        CREATE TABLE IF NOT EXISTS currencies (
            key TEXT PRIMARY KEY, value INTEGER NOT NULL, description TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS marriages (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user1_id INTEGER NOT NULL,
            user2_id INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user1_id, user2_id)
        );

        CREATE TABLE IF NOT EXISTS children (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            parent1_id INTEGER NOT NULL,
            parent2_id INTEGER,
            name TEXT NOT NULL,
            age INTEGER NOT NULL DEFAULT 0,
            happiness INTEGER NOT NULL DEFAULT 80,
            health INTEGER NOT NULL DEFAULT 100,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
